import Head from 'next/head';
import { fetchTopRatedTV, Identificator } from '@/utils/requests';
import Movies from '@/components/movies/Movies';

import Heading from '@/components/ui/Heading';
import React, { Fragment, useRef, useState } from 'react';
import useInfinityFetch from '@/hooks/useInfinityFetch';
import { Movie } from 'types';
import Section from '@/components/movies/Section';
import LoadingSpinner from '@/components/ui/LoadingSpinner';

export default function Series() {
  const loadMoreButtonRef = useRef<HTMLButtonElement>(null);
  const [seriesType, _] = useState<Identificator>('tvShow');
  const {
    fetchNextPage,
    hasNextPage,
    isLoading,
    isError,
    error,
    data,
    isFetching,
    isFetchingNextPage,
  } = useInfinityFetch(
    'newInfiniteTopRatedSeries',
    loadMoreButtonRef,
    fetchTopRatedTV
  );

  const values = {
    fetchNextPage,
    hasNextPage,
    data,
    isFetching,
    isFetchingNextPage,
    loadMoreButtonRef,
  };

  if (isLoading) {
    return <LoadingSpinner />;
  }

  if (isError) {
    return <h2>{error?.message} </h2>;
  }
  return (
    <>
      <Head>
        <title>Popular series</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section {...values} type={seriesType} />
    </>
  );
}
